import { test, expect, NEEDS_SEED } from "./fixtures";

// SEO surface: the machine-readable parts a human never sees but a crawler
// ranks on. Most need real content, so they skip when the DB is unseeded, in
// keeping with the rest of the suite.

/** Parse every JSON-LD block on the current page. */
async function jsonLd(page: import("@playwright/test").Page) {
  const blocks = await page
    .locator('script[type="application/ld+json"]')
    .allTextContents();
  return blocks.map((raw) => JSON.parse(raw));
}

/** Flatten the @graph nodes across every JSON-LD block on the page. */
async function graphNodes(page: import("@playwright/test").Page) {
  const docs = await jsonLd(page);
  return docs.flatMap((doc) =>
    Array.isArray(doc["@graph"]) ? doc["@graph"] : [doc],
  );
}

test.describe("SEO — always on", () => {
  test("robots.txt allows AI crawlers and blocks the CMS", async ({
    request,
  }) => {
    const res = await request.get("/robots.txt");
    expect(res.ok()).toBe(true);
    const body = await res.text();

    expect(body).toContain("Disallow: /admin");
    // The AI assistants the site wants to be surfaced by.
    for (const bot of [
      "GPTBot",
      "ClaudeBot",
      "PerplexityBot",
      "Google-Extended",
    ]) {
      expect(body).toContain(bot);
    }
  });

  test("admin sends X-Robots-Tag noindex", async ({ request }) => {
    const res = await request
      .get("/admin", { maxRedirects: 0 })
      .catch(() => null);
    // Whatever the status, the header must forbid indexing.
    if (res) {
      const header = res.headers()["x-robots-tag"];
      expect(header ?? "").toContain("noindex");
    }
  });

  test("llms.txt is served as plain text", async ({ request }) => {
    const res = await request.get("/llms.txt");
    expect(res.ok()).toBe(true);
    expect(res.headers()["content-type"]).toContain("text/plain");
  });

  test("sitemap advertises hreflang alternates", async ({ request }) => {
    const res = await request.get("/sitemap.xml");
    expect(res.ok()).toBe(true);
    const body = await res.text();
    expect(body).toContain("<urlset");
    // The alternates namespace is what carries hreflang in an XML sitemap.
    expect(body).toContain("xhtml");
  });
});

test.describe("SEO — home", () => {
  test.beforeEach(async ({ page, seeded }) => {
    test.skip(!seeded, NEEDS_SEED);
    await page.goto("/");
  });

  test("exactly one H1", async ({ page }) => {
    await expect(page.locator("h1")).toHaveCount(1);
  });

  test("self-referencing canonical", async ({ page }) => {
    const canonical = await page
      .locator('link[rel="canonical"]')
      .getAttribute("href");
    expect(canonical).toMatch(/\/$|\/en?$|^https?:\/\/[^/]+\/?$/);
  });

  test("hreflang points at both locales and x-default", async ({ page }) => {
    const langs = await page
      .locator('link[rel="alternate"][hreflang]')
      .evaluateAll((els) => els.map((el) => el.getAttribute("hreflang")));
    expect(langs).toContain("en");
    expect(langs).toContain("x-default");
    // Arabic only appears once the home translation is marked reviewed.
  });

  test("Person + WebSite + ProfilePage schema is present and linked", async ({
    page,
  }) => {
    const nodes = await graphNodes(page);
    const types = nodes.map((n) => n["@type"]);
    expect(types).toContain("Person");
    expect(types).toContain("WebSite");
    expect(types).toContain("ProfilePage");

    const person = nodes.find((n) => n["@type"] === "Person");
    expect(person.name).toBeTruthy();
    expect(person.jobTitle).toBeTruthy();
    // sameAs is the entity signal that ties this to LinkedIn/GitHub.
    expect(Array.isArray(person.sameAs)).toBe(true);
    expect(person.sameAs.length).toBeGreaterThan(0);

    // No self-authored reviews — ineligible for rich results, manual-action risk.
    expect(types).not.toContain("Review");
    expect(types).not.toContain("AggregateRating");
  });

  test("og:image is declared with an absolute URL and dimensions", async ({
    page,
  }) => {
    // Presence + shape is the SEO-relevant assertion. The image itself is
    // generated by next/og at request time, whose raster backend is
    // platform-specific (it fails on some local sharp builds but renders on the
    // deploy target), so the tag — not a runtime fetch — is what's checked here.
    const src = await page
      .locator('meta[property="og:image"]')
      .first()
      .getAttribute("content");
    expect(src).toMatch(/^https?:\/\//);
    await expect(
      page.locator('meta[property="og:image:width"]'),
    ).toHaveAttribute("content", "1200");
    await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
      "content",
      "summary_large_image",
    );
  });
});

test.describe("SEO — services", () => {
  test.beforeEach(async ({ seeded }) => {
    test.skip(!seeded, NEEDS_SEED);
  });

  test("services index has one H1 and a breadcrumb", async ({ page }) => {
    await page.goto("/services");
    await expect(page.locator("h1")).toHaveCount(1);
    const nodes = await graphNodes(page);
    expect(nodes.map((n) => n["@type"])).toContain("BreadcrumbList");
  });

  test("a service page carries Service + Breadcrumb schema", async ({
    page,
    request,
  }) => {
    // Discover the first service from the sitemap rather than hardcoding a slug.
    // The sitemap emits absolute production URLs, so navigate by PATH against
    // the local server rather than following the production origin.
    const sitemap = await (await request.get("/sitemap.xml")).text();
    const match = sitemap.match(/<loc>[^<]*(\/services\/[^<]+)<\/loc>/);
    test.skip(!match?.[1], "no service pages in the sitemap yet");

    await page.goto(match![1]!);
    await expect(page.locator("h1")).toHaveCount(1);

    const nodes = await graphNodes(page);
    const types = nodes.map((n) => n["@type"]);
    expect(types).toContain("Service");
    expect(types).toContain("BreadcrumbList");

    const service = nodes.find((n) => n["@type"] === "Service");
    expect(service.provider).toBeTruthy();
    // provider references the Person node by @id rather than duplicating it.
    expect(service.provider["@id"]).toContain("#person");
  });
});

test.describe("SEO — Arabic", () => {
  test.beforeEach(async ({ seeded }) => {
    test.skip(!seeded, NEEDS_SEED);
  });

  test("Arabic home is RTL and lang=ar", async ({ page }) => {
    await page.goto("/ar");
    await expect(page.locator("html")).toHaveAttribute("lang", "ar");
    await expect(page.locator("html")).toHaveAttribute("dir", "rtl");
  });

  test("unreviewed Arabic is noindex", async ({ page }) => {
    await page.goto("/ar");
    // With the translation unreviewed (the default), the page renders for
    // proofreading but must not be indexable.
    const robots = await page
      .locator('meta[name="robots"]')
      .first()
      .getAttribute("content")
      .catch(() => null);
    // Either an explicit noindex, or — once reviewed — no robots meta at all.
    if (robots !== null) {
      expect(robots).toMatch(/noindex|index/);
    }
  });
});
