/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    skills: Skill;
    experience: Experience;
    education: Education;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    media: Media;
    users: User;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Picks the glyph on the card.
   */
  icon: 'code' | 'automation' | 'payments' | 'data';
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * How-I-work skills and the tech stack. Filter by category to see one or the other.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  /**
   * Lower numbers appear first within a category.
   */
  order?: number | null;
  /**
   * Which block of the Skills section this appears in.
   */
  category: 'soft' | 'tech';
  /**
   * Shown verbatim, e.g. "Stripe" or "Clear Communication".
   */
  name: string;
  /**
   * Optional grouping, to keep a long tech list browsable.
   */
  area?: ('payments' | 'cloud' | 'data' | 'messaging' | 'search' | 'api') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  title: string;
  company: string;
  /**
   * Company website URL.
   */
  website?: string | null;
  from: string;
  isPresent?: boolean | null;
  to?: string | null;
  /**
   * One responsibility per line. Lines are rendered as bullets.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  degree: string;
  institution: string;
  from: string;
  to?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  title: string;
  /**
   * Product name on its own, without the descriptor in brackets — used on cards and in the hero metric strip.
   */
  shortName?: string | null;
  /**
   * Matches a screenshot in public/case-studies/<slug>.jpg, used when no thumbnail is uploaded.
   */
  slug?: string | null;
  /**
   * Live site URL.
   */
  link?: string | null;
  /**
   * Screenshot of the live site. Falls back to public/case-studies/<slug>.jpg, then to a gradient.
   */
  thumbnail?: (string | null) | Media;
  /**
   * The single number this project is remembered by. Shown on the card and in the hero strip.
   */
  metric?: {
    /**
     * Optional starting value, e.g. 200.
     */
    before?: string | null;
    /**
     * e.g. 13,000 or 60%.
     */
    value?: string | null;
    direction?: ('up' | 'down') | null;
    /**
     * What the number measures, e.g. product imports / day.
     */
    label?: string | null;
  };
  star?: {
    situation?: string | null;
    task?: string | null;
    /**
     * One action per line. Lines are rendered as bullets.
     */
    action?: string | null;
    /**
     * One result per line. Lines are rendered as bullets.
     */
    result?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  quote: string;
  author: string;
  role?: string | null;
  company?: string | null;
  /**
   * Marks dummy content to replace later.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
  };
  skills?: {
    /**
     * Allow clients to find skills.
     */
    find?: boolean | null;
    /**
     * Allow clients to create skills.
     */
    create?: boolean | null;
    /**
     * Allow clients to update skills.
     */
    update?: boolean | null;
  };
  experience?: {
    /**
     * Allow clients to find experience.
     */
    find?: boolean | null;
    /**
     * Allow clients to create experience.
     */
    create?: boolean | null;
    /**
     * Allow clients to update experience.
     */
    update?: boolean | null;
  };
  education?: {
    /**
     * Allow clients to find education.
     */
    find?: boolean | null;
    /**
     * Allow clients to create education.
     */
    create?: boolean | null;
    /**
     * Allow clients to update education.
     */
    update?: boolean | null;
  };
  caseStudies?: {
    /**
     * Allow clients to find case-studies.
     */
    find?: boolean | null;
    /**
     * Allow clients to create case-studies.
     */
    create?: boolean | null;
    /**
     * Allow clients to update case-studies.
     */
    update?: boolean | null;
  };
  testimonials?: {
    /**
     * Allow clients to find testimonials.
     */
    find?: boolean | null;
    /**
     * Allow clients to create testimonials.
     */
    create?: boolean | null;
    /**
     * Allow clients to update testimonials.
     */
    update?: boolean | null;
  };
  profile?: {
    /**
     * Allow clients to find profile global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update profile global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'experience';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'education';
        value: string | Education;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  order?: T;
  icon?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  order?: T;
  category?: T;
  name?: T;
  area?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  company?: T;
  website?: T;
  from?: T;
  isPresent?: T;
  to?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  order?: T;
  degree?: T;
  institution?: T;
  from?: T;
  to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  shortName?: T;
  slug?: T;
  link?: T;
  thumbnail?: T;
  metric?:
    | T
    | {
        before?: T;
        value?: T;
        direction?: T;
        label?: T;
      };
  star?:
    | T
    | {
        situation?: T;
        task?: T;
        action?: T;
        result?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  order?: T;
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  skills?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  experience?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  education?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  caseStudies?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  testimonials?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  profile?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identity, bio and contact details. Services, skills and case studies each live in their own collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: string;
  name: string;
  age?: number | null;
  /**
   * Short role tagline, e.g. "Senior Software Engineer".
   */
  headline: string;
  /**
   * Hero photo. Falls back to a silhouette placeholder if empty.
   */
  heroImage?: (string | null) | Media;
  /**
   * Narrative bio. Blank lines separate paragraphs.
   */
  about: string;
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Ticked, the phone number above powers the WhatsApp chat link. Untick to use a different number.
     */
    phoneIsWhatsapp?: boolean | null;
    /**
     * International format, e.g. +20 112 846 8458. Blank means no WhatsApp link.
     */
    whatsapp?: string | null;
    /**
     * LinkedIn and WhatsApp also surface in the hero. Every link here is listed in the Contact section.
     */
    links?:
      | {
          /**
           * Sets the icon and the default name.
           */
          platform:
            | 'linkedin'
            | 'github'
            | 'whatsapp'
            | 'x'
            | 'instagram'
            | 'facebook'
            | 'youtube'
            | 'telegram'
            | 'stackoverflow'
            | 'medium'
            | 'website'
            | 'other';
          /**
           * Name to show. Required for "Other".
           */
          label?: string | null;
          /**
           * Full URL including https://. For WhatsApp use a wa.me link.
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  age?: T;
  headline?: T;
  heroImage?: T;
  about?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        phoneIsWhatsapp?: T;
        whatsapp?: T;
        links?:
          | T
          | {
              platform?: T;
              label?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}